name: hamekare_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0

  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  get: ^4.6.5
  dio: ^5.0.3
  logger: ^1.1.0
  flutter_email_sender: ^5.2.0
  intl: 0.18.1
  persian: ^1.2.0
  pin_code_fields: ^7.4.0
  url_launcher: ^6.1.7
  curved_navigation_bar: ^1.0.3
  fluttertoast: ^8.1.2
  persian_tools: ^1.0.3
  image_picker: ^0.8.6
  carousel_slider: ^4.2.0
  smooth_page_indicator: ^1.0.0+2
  flutter_web_frame: ^0.0.3
  lottie: ^2.0.0
  expandable: ^5.0.1
  flutter_rating_bar: ^4.0.1
  permission_handler: ^10.2.0
  http: ^0.13.5
  bottom_navy_bar: ^6.0.0
  chewie: ^1.3.6
  video_player: ^2.4.9
  shamsi_date: ^1.0.1
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/nodata.png
    - assets/video/
    - assets/lottie/
    - assets/image/intro/

  fonts:
    - family: iranrounded
      fonts:
        - asset: assets/font/iranrounded.ttf
