name: hamekare_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  get: ^4.6.6
  dio: ^5.4.1
  logger: ^2.1.0
  flutter_email_sender: ^6.0.2
  intl: ^0.19.0
  persian: ^1.2.0
  pin_code_fields: ^8.0.1
  url_launcher: ^6.2.5
  curved_navigation_bar: ^1.0.3
  fluttertoast: ^8.2.4
  persian_tools: ^1.0.3
  image_picker: ^1.0.7
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_web_frame: ^1.0.0
  lottie: ^3.1.0
  expandable: ^5.0.1
  flutter_rating_bar: ^4.0.1
  permission_handler: ^11.3.0
  http: ^1.2.0
  bottom_navy_bar: ^6.0.0
  chewie: ^1.7.5
  video_player: ^2.8.2
  shamsi_date: ^1.0.2
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/nodata.png
    - assets/video/
    - assets/lottie/
    - assets/image/intro/

  fonts:
    - family: iranrounded
      fonts:
        - asset: assets/font/iranrounded.ttf
